HOPSWORKS-493 (#1)
* [MINOR] Addressed Docs dependency security vulnerability

Addressed issue raised on mailing list:
https://www.mail-archive.com/devlivy.incubator.apache.org/msg00295.html

More info on the vulnerability:
https://snyk.io/blog/nokogiri-xxe-vulnerabilities/

Author: Alex Bozarth <ajbozart@us.ibm.com>

Closes #75 from ajbozarth/fix.

(cherry picked from commit 26428c56f20ba5ea608038ed8c2e11d8f04665d4)
Signed-off-by: Alex Bozarth <ajbozart@us.ibm.com>

* [MINOR][BUILD] Improve release-build script

Improved release-build.sh based on the 0.5.0-incubating release process.

Includes:

- Instead of forcing user to set env it prompts for required info, this also protects password inout
- Creates temp dir to hold files created in release process and makes sure git ignores it

Author: Alex Bozarth <ajbozart@us.ibm.com>

Closes #76 from ajbozarth/script.

* [LIVY-448] Assembly format is duplicated in pom.xml and assembly.xml

## What changes were proposed in this pull request?
The assembly format for Livy is specified twice:
1 in `assembly/pom.xml`:
```xml
              <formats>
                <format>${assembly.format}</format>
              </formats>
```
2 in `assembly/assembly.xml`
```
              <formats>
                <format>zip</format>
              </formats>
```
But only one is enough. Also in `assembly/assembly.xml`, the format is hard coded as zip, but is should be based

## How was this patch tested?
All the unit tests and ITs pass as usual. Moreover, I tested that  `targz` profile builds a tar.gz archive and the default profile builds a zip archive.

For example,
this builds the zip archive:
```
mvn -am -pl assembly package
```
And this builds the tar.gz artifact:
```
mvn -Ptargz -am -pl assembly package
```

Task-url: https://issues.apache.org/jira/browse/LIVY-448

Author: Meisam <meisam@Hachinohe.local>

Closes #83 from meisam/LIVY-448.

* [LIVY-446][BUILD] Livy to Support Spark 2.3

## What changes were proposed in this pull request?

This PR aims to support Spark 2.3 in Livy, several changes due to internal changes of Spark 2.3

## How was this patch tested?

Existing UTs.

Author: jerryshao <sshao@hortonworks.com>

Closes #81 from jerryshao/LIVY-446.

* change org.apache.hadoop to io.hops

* add troubleshoot to README

diff --git a/bin/livy-server b/bin/livy-server
--- a/bin/livy-server
+++ b/bin/livy-server
@@ -85,7 +85,19 @@ start_livy_server() {
     exit 1
   fi
 
-  LIVY_CLASSPATH="$LIBDIR/*:$LIVY_CONF_DIR"
+  export HADOOP_CLASSPATH=$(${HADOOP_CONF_DIR}/../../bin/hadoop classpath)
+  echo "Appending to classpath the Hadoop classpath: $HADOOP_CLASSPATH"
+  if [ $? -ne 0 ]; then
+      echo "Could not find Hadoop classpath using '$HADOOP_HOME/bin/hadoop classpath'. HADOOP_HOME was: $HADOOP_HOME"
+      exit 2
+  fi
+  SPARK_JARS_DIR=${SPARK_HOME}/jars
+  if [ ! -d $SPARK_JARS_DIR ]; then
+    echo "Could not find Spark jars directory in ${SPARK_CONF_DIR}/../jars." 1>&2
+    exit 3
+  fi
+
+  LIVY_CLASSPATH="$LIBDIR/*:$LIVY_CONF_DIR:$HADOOP_CLASSPATH:$SPARK_JARS_DIR/*"
 
   if [ -n "$SPARK_CONF_DIR" ]; then
     LIVY_CLASSPATH="$LIVY_CLASSPATH:$SPARK_CONF_DIR"
